{
	"version": 1561823207,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/btnachievement-sheet0.png",
		"images/btnleaderboard-sheet0.png",
		"images/btnads-sheet0.png",
		"images/btngoogleplay-sheet0.png",
		"images/btnaddsite-sheet0.png",
		"images/btnvideo-sheet0.png",
		"images/btnmoregames-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/btnmusic-sheet0.png",
		"images/btnmusic-sheet1.png",
		"images/btnoption-sheet0.png",
		"images/btnresume-sheet0.png",
		"images/btnincreasespeed-sheet0.png",
		"images/btnincreasespeed-sheet1.png",
		"images/btnhome-sheet0.png",
		"images/btnkiz10-sheet0.png",
		"images/btnmore-sheet0.png",
		"images/btnretry-sheet0.png",
		"images/btnbuy-sheet0.png",
		"images/btnbuygold-sheet0.png",
		"images/btnnext-sheet0.png",
		"images/btnprev-sheet0.png",
		"images/btnupgrade-sheet0.png",
		"images/btnshopcoin-sheet0.png",
		"images/btnspecial-sheet0.png",
		"images/btntower0-sheet0.png",
		"images/btntower0-sheet1.png",
		"images/btntower1-sheet0.png",
		"images/btntower2-sheet0.png",
		"images/btntower3-sheet0.png",
		"images/btntowerupgrade-sheet0.png",
		"images/btntowerupgrade-sheet1.png",
		"images/btnsell-sheet0.png",
		"images/btnspawnenemy-sheet0.png",
		"images/btntower4-sheet0.png",
		"images/btntower5-sheet0.png",
		"images/btntower6-sheet0.png",
		"images/btnlevel1-sheet0.png",
		"images/btnlevel1-sheet1.png",
		"images/btnlevel2-sheet0.png",
		"images/btnlevel3-sheet0.png",
		"images/btnlevel4-sheet0.png",
		"images/btnlevel5-sheet0.png",
		"images/btnlevel6-sheet0.png",
		"images/btnlevel7-sheet0.png",
		"images/btnlevel8-sheet0.png",
		"images/btnlevel9-sheet0.png",
		"images/btnlevel10-sheet0.png",
		"images/btnlevel11-sheet0.png",
		"images/btnlevel12-sheet0.png",
		"images/btnlevel-sheet0.png",
		"images/btnlevel-sheet1.png",
		"images/btnlevel-sheet2.png",
		"images/bg-sheet0.png",
		"images/bg1-sheet0.png",
		"images/bg2-sheet0.png",
		"images/bg3-sheet0.png",
		"images/bgoverlay-sheet0.png",
		"images/bgmap1-sheet0.png",
		"images/bgmap2-sheet0.png",
		"images/bgmap3-sheet0.png",
		"images/bg4-sheet0.png",
		"images/bg5-sheet0.png",
		"images/bg6-sheet0.png",
		"images/txtgold.png",
		"images/txtkill.png",
		"images/txtprice.png",
		"images/txtinfoupgrade.png",
		"images/bgpreloader-sheet0.png",
		"images/uiloading-sheet0.png",
		"images/fresult-sheet0.png",
		"images/uikill-sheet0.png",
		"images/uibonus-sheet0.png",
		"images/uiwinlose-sheet0.png",
		"images/effectshine-sheet0.png",
		"images/transition-sheet0.png",
		"images/spr1024x450-sheet0.png",
		"images/rotatescreen-sheet0.png",
		"images/cam-sheet0.png",
		"images/foption-sheet0.png",
		"images/fwood-sheet0.png",
		"images/flife-sheet0.png",
		"images/fwave-sheet0.png",
		"images/fgold-sheet0.png",
		"images/ftowerbuild-sheet0.png",
		"images/game-sheet0.png",
		"images/tile.png",
		"images/tree.png",
		"images/stage-sheet0.png",
		"images/barspecial-sheet0.png",
		"images/fbarenemy-sheet0.png",
		"images/barenemy-sheet0.png",
		"images/bartower-sheet0.png",
		"images/fbartower-sheet0.png",
		"images/ftowerprice-sheet0.png",
		"images/level-sheet0.png",
		"images/level-sheet1.png",
		"images/kingdom-sheet0.png",
		"images/skull-sheet0.png",
		"images/mask-sheet0.png",
		"images/barspawnenemy-sheet0.png",
		"images/wood-sheet0.png",
		"images/pointrotate-sheet0.png",
		"images/targetmeteor-sheet0.png",
		"images/towerbuild-sheet0.png",
		"images/tower0-sheet0.png",
		"images/tower0-sheet1.png",
		"images/tower3-sheet0.png",
		"images/tower3-sheet1.png",
		"images/tower1-sheet0.png",
		"images/tower1-sheet1.png",
		"images/tower2-sheet0.png",
		"images/flag-sheet0.png",
		"images/tower4-sheet0.png",
		"images/tower4-sheet1.png",
		"images/tower5-sheet0.png",
		"images/tower5-sheet1.png",
		"images/tower6-sheet0.png",
		"images/tower6-sheet1.png",
		"images/enemy3-sheet0.png",
		"images/enemy3-sheet1.png",
		"images/enemy0-sheet0.png",
		"images/enemy0-sheet1.png",
		"images/enemy1-sheet0.png",
		"images/enemy1-sheet1.png",
		"images/enemy2-sheet0.png",
		"images/enemy4-sheet0.png",
		"images/enemy4-sheet1.png",
		"images/boss0-sheet0.png",
		"images/enemy5-sheet0.png",
		"images/enemy6-sheet0.png",
		"images/enemy6-sheet1.png",
		"images/enemy7-sheet0.png",
		"images/enemy8-sheet0.png",
		"images/enemy9-sheet0.png",
		"images/enemy9-sheet1.png",
		"images/boss1-sheet0.png",
		"images/effectbuild-sheet0.png",
		"images/effectbuild-sheet1.png",
		"images/effectenemydie-sheet0.png",
		"images/effectenemydie-sheet1.png",
		"images/effecttowerice-sheet0.png",
		"images/effecttowercannon-sheet0.png",
		"images/effecttowerpoison-sheet0.png",
		"images/effecttowerpoison-sheet1.png",
		"images/effectexplosion-sheet0.png",
		"images/effectpoison-sheet0.png",
		"images/effectpoison-sheet1.png",
		"images/effecthole-sheet0.png",
		"images/effecthole-sheet1.png",
		"images/effectrocket-sheet0.png",
		"images/effectlaser-sheet0.png",
		"images/effectlightning-sheet0.png",
		"images/effectbullet5a-sheet0.png",
		"images/effectbullet5b-sheet0.png",
		"images/bullet0-sheet0.png",
		"images/bullet1-sheet0.png",
		"images/bullet2-sheet0.png",
		"images/bullet3-sheet0.png",
		"images/bulletmeteor-sheet0.png",
		"images/bullet4a-sheet0.png",
		"images/bullet4a-sheet1.png",
		"images/bullet5a-sheet0.png",
		"images/bullet4b-sheet0.png",
		"images/bullet4b-sheet1.png",
		"images/bullet5b-sheet0.png",
		"images/bullet6-sheet0.png",
		"images/bullet6-sheet1.png",
		"images/bullet6-sheet2.png",
		"images/uibuychar-sheet0.png",
		"images/uibuychar-sheet1.png",
		"images/uibuychar-sheet2.png",
		"images/uibuygold-sheet0.png",
		"images/uigold-sheet0.png",
		"images/fshopgold-sheet0.png",
		"images/uititle-sheet0.png",
		"images/fupgrade-sheet0.png",
		"images/fupgrade-sheet1.png",
		"images/uiupgradelevel-sheet0.png",
		"images/uilevelmax-sheet0.png",
		"images/flevel-sheet0.png",
		"images/ftutorial-sheet0.png",
		"images/buildtowerposition-sheet0.png",
		"images/tower-sheet0.png",
		"images/arrow-sheet0.png",
		"images/tilemap.png",
		"images/levelpointer-sheet0.png",
		"media/in game.m4a",
		"media/in game.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"media/button prev next.m4a",
		"media/button prev next.ogg",
		"media/button.m4a",
		"media/button.ogg",
		"media/buy.m4a",
		"media/gold.m4a",
		"media/gold.ogg",
		"media/hit enemy.m4a",
		"media/hit enemy.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"media/not enough gold.m4a",
		"media/not enough gold.ogg",
		"media/power up.m4a",
		"media/power up.ogg",
		"media/select.m4a",
		"media/select.ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/buy.ogg",
		"media/build.m4a",
		"media/build.ogg",
		"media/get wood.m4a",
		"media/get wood.ogg",
		"media/tower.m4a",
		"media/tower.ogg",
		"media/wood.m4a",
		"media/wood.ogg",
		"media/explode boss.m4a",
		"media/explode boss.ogg",
		"media/explode cannon ball.m4a",
		"media/explode cannon ball.ogg",
		"media/explode castle.m4a",
		"media/explode castle.ogg",
		"media/explode enemy.m4a",
		"media/explode enemy.ogg",
		"media/explode meteor.m4a",
		"media/explode meteor.ogg",
		"media/hit castle.m4a",
		"media/hit castle.ogg",
		"media/meteor fall.m4a",
		"media/meteor fall.ogg",
		"media/tower 0 attack.m4a",
		"media/tower 0 attack.ogg",
		"media/tower 1 attack.m4a",
		"media/tower 1 attack.ogg",
		"media/tower 2 attack.m4a",
		"media/tower 2 attack.ogg",
		"media/tower 3 attack.m4a",
		"media/tower 3 attack.ogg",
		"media/upgrade tower 0 lvl 2.m4a",
		"media/upgrade tower 0 lvl 2.ogg",
		"media/upgrade tower 1 lvl 2.m4a",
		"media/upgrade tower 1 lvl 2.ogg",
		"media/upgrade tower 2 lvl 2.m4a",
		"media/upgrade tower 2 lvl 2.ogg",
		"media/upgrade tower 3 lvl 2.m4a",
		"media/upgrade tower 3 lvl 2.ogg",
		"media/upgrade tower lvl 1.m4a",
		"media/upgrade tower lvl 1.ogg",
		"media/tower 5 attack.m4a",
		"media/tower 5 attack.ogg",
		"media/tower 4 attack.m4a",
		"media/tower 4 attack.ogg",
		"media/tower 6 attack.m4a",
		"media/tower 6 attack.ogg",
		"media/upgrade tower 4 lvl 2.m4a",
		"media/upgrade tower 4 lvl 2.ogg",
		"media/upgrade tower 5 lvl 2.m4a",
		"media/upgrade tower 5 lvl 2.ogg",
		"media/upgrade tower 6 lvl 2.m4a",
		"media/upgrade tower 6 lvl 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}